trigger:
 - main
pool:
 vmImage: ubuntu-latest

variables:
  imageName: 'dhanuregistry'

stages:
  - stage: Build
    jobs:
      - job: BuildPush
        steps:
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs: 
             containerRegistry: 'acr-connection'
             repository: '$(imageName)'
             Dockerfile: '**/app/Dockerfile'
             command: 'buildAndPush'
             tags: |
               latest
               $(Build.BuildId)