trigger:
  - main

pool:
 vmImage: ubuntu-latest

variables:
  imageName: motivational-app

stages:
  - stage: Build
    jobs:
      - job: BuildandPush
        steps:
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              containerRegistry: 'motivational-acr-connection'
              repository: '$(imageName)'
              Dockerfile: '**/motivational-website/Dockerfile'
              command: 'buildAndPush'
              tags: |
               $(Build.BuildId)
             