trigger:
  - main

pool:
 vmImage: ubuntu-latest

 steps:
   - task: Docker@2
     displayName: 
     inputs:
       ContainerRegistry: 'acr-connection'
       repository: 'dhanuregistry'
       command: 'buildAndPush'
       Dockerfile: '**/quote-generator-app/Dockerfile'
       tag: |
         v1
         