trigger:
  - main

pool:
 vmImage: ubuntu-latest

variables:
  imageName: portfolio-app
stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
             containerRegistry: 'acr-connection'
             repository: '$(imageName)'
             Dockerfile: '**/portfolio-app/Dockerfile'
             command: buildAndPush
             tags: |
               $(Build.BuildID)