apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-container
          image: dhanuregistry.azurecr.io/portfolio-app:v3
          resources:
            limits:
              cpu: "300m"
              memory: "150Mi"
            requests:
              cpu: "256m"
              memory: "140Mi"
          ports:
            - containerPort: 5000
          env:
            - name: APP_Version
              valueFrom:
                configMapKeyRef:
                    name: portfolio-app-config
                    key: APP_Version

            - name: APP_Name
              valueFrom:
                configMapKeyRef:
                    name: portfolio-app-config
                    key: APP_Name
           
            - name: App_Username
              valueFrom:
                secretKeyRef:
                    name: portfolio-app-secret
                    key: App_Username
            
            - name: App_Password
              valueFrom:
                secretKeyRef:
                    name: portfolio-app-secret
                    key: APP_Password
                  

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-service
spec:
  type: LoadBalancer
  selector:
    app: portfolio-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
