apiVersion: apps/v1
kind: Deployment 
metadata:
   name: quote-generator-app-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: quote-generator-app
   template:
      metadata:
        labels:
           app: quote-generator-app
      spec:
        containers:
           - name: quote-generator-app
             image: quote-generator-app:v1
             ports:
                - containerPort: 5000
             resources:
                limits:
                   memory: "1000Mi"
                   cpu: "700m"
                requests:
                   memory: "689Mi"
                   cpu: "589m"
---
apiVersion: v1
kind: Service 
metadata:
  name: quote-generator-app-service
spec:
  selector:
     app: quote-generator-app
  type: NodePort
  ports:
     - port: 80
       targetPort: 5000
       nodePort: 30003