apiVersion: apps/v1
kind: Deployment
metadata:
   name: notes-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
       labels:
         app: notes-app
    spec:
      containers:
        - name: notes-app-container
          image: dhanu1996/notes-app:v2
          env:
            - name: APP_NAME
              valueFrom:
                 configMapKeyRef:
                   name: notes-app-config
                   key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: notes-app-config
                  key: APP_ENV
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "500m"
              memory: "200Mi"
            requests:
              cpu: "200m"
              memory: "177Mi"

            
---
apiVersion: v1
kind: Service 
metadata:
  name: notes-app-service
spec: 
  selector: 
    app: notes-app
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 5000
      nodePort: 30008



      